name: main
on:
  pull_request:
  push:
    branches: [master]
  schedule:
    - cron: '30 8 * * 0'

jobs:
  main:
    name: main
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: bin/set-tag >> "$GITHUB_ENV"
    - run: bin/build "$TAG"
    - run: bin/test "$TAG"
    - run: bin/push "$TAG"
      env:
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
      if: github.event_name != 'pull_request'
