name: main
on:
  pull_request:
  push:
    branches: [master]

jobs:
  main:
    name: main
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: echo "TAG=$(bin/set-tag)" >> "$GITHUB_ENV"
      name: set tag
    - run: docker build --pull --tag "$TAG" .
    - run: bin/test "$TAG"
    - run: bin/push "$TAG"
      env:
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: github.event_name != 'pull_request'
